version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8888:8888"
    environment:
      - DATABASE_URL=sqlite:///./data_contracts.db
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - ALLOWED_ORIGINS=["http://localhost:3333"]
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8888/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3333:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8888/api/v1
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_data:
